### ISSUE TITLE
coarse、middle、fine三种粒度下数据的区别

### ISSUE THREAD

**Issue by qqliang** [THU-KEG/MOOC-Radar#1]
作者您好！我从链接中下载了三种粒度的数据，发现三个文件下problem.json和student-problem-xx.json内的数据是一样的，请问这三种粒度数据的区别是什么呢？
![image](https://github.com/THU-KEG/MOOC-Radar/assets/23022359/960c8253-ad15-449a-8dde-cd6060ba5649)

**Comment by yujifan0326** [comment]
您好，problem.json确实是一致的，但是student-problem-coarse.json并不完全一致，主要在于提供的做题记录里是否标识了它的Exercise id或Course id等(尽管这些信息也可以在problem_id中映射出来)。

这几个数据文件的划分主要是为了方便开发的时候，提醒所希望选择的concept粒度，而非为了增加难度（因为这个数据资源并非目标是评估哪些模型更好）。在开发的时候，可以从Raw data或选定一个粒度的文件开始，希望数据集对您有帮助！

**Comment by 819114173** [comment]
> 
请问代码如何运行，我咋运行不了，小白求助
